name = "cloudflare-saas-stack"
compatibility_date = "2024-09-03"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "edge-haven-db"
database_id = "61c0d36a-9013-4eba-93ac-171c597a578f"
migrations_dir = "./drizzle"
